email: hello@timbest.net
url: "https://timothy.best"
repository: timbest/timbest.github.io

github: [metadata]
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/media"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
